---
site_name: "LAB-1451: Deep-dive into Cisco devices xAPIs" # This must begin with the session ID, e.g. LABXXX-1234 This is my Cisco Live Lab
dev_addr: 127.0.0.1:8001
site_description: "Deep-dive into Cisco devices xAPIs" # must be same as "site_name"
site_author: Bobby McGonigle
copyright: Copyright &copy; 2025 Cisco
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - navigation.footer
    - search.suggest
    - content.code.copy
    - toc.integrate
  custom_dir: docs/overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: template_assets/webexLogo91.png
  favicon: template_assets/webex75.png
extra:
  generator: false
  repo: "https://github.com/WebexCC-SA/LAB-1451.git"
  site_event: test
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - template_assets/js/newLoad.js
  - template_assets/js/setInfo.js
plugins:
  - search
  - macros
  # - with-pdf:
  #     cover_title: LABXXX-1234
  #     cover_subtitle: My famous WebexOne Lab
  #     cover_logo: template_assets/Wx1_25_PDF_image.jpg
  - glightbox:
      touchNavigation: true
      loop: false
      effect: fade
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: false
      skip_classes:
      - custom-skip-class-name
      auto_caption: true
      caption_position: top
markdown_extensions:
  - md_in_html
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - tables
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
      
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Home: index.md
  - Lab Prerequisites:
    - Introduction: Main-Lab/Prerequisites/prq_intro.md
    - RoomOS: Main-Lab/Prerequisites/prq_roomOs.md
    - PhoneOS: Main-Lab/Prerequisites/prq_phoneOs.md
    - Deployment: Main-Lab/Prerequisites/prq_deployment.md
  - RoomOS xAPI & Extensions: 
    - RoomOS xAPI & Extensions: Main-Lab/RoomOS/rxp_intro.md
    - RoomOS xAPI:
      - Intro to RoomOS xAPI: Main-Lab/RoomOS/rxp_xapi/rxp_xapi_intro.md
      - Terminal: Main-Lab/RoomOS/rxp_xapi/rxp_xapi_terminal.md
      - HTTP: Main-Lab/RoomOS/rxp_xapi/rxp_xapi_http.md
      - WebSockets: Main-Lab/RoomOS/rxp_xapi/rxp_xapi_websockets.md
      - Cloud: Main-Lab/RoomOS/rxp_xapi/rxp_xapi_cloud.md
      - Macros: Main-Lab/RoomOS/rxp_xapi/rxp_xapi_macros.md
    - RoomOS Extensions: 
      - Introduction: Main-Lab/RoomOS/rxp_userInterface/rxp_ui_intro.md
    - Solution Exercises:
      - Introduction: Main-Lab/RoomOS/rxp_exercises/rxp_exe_intro.md
  - PhoneOS xAPI: 
    - Introduction: Main-Lab/PhoneOS/pxp_intro.md
    - Conclusion: Main-Lab/Deployment/dep_conclusion.md
  - Deployment: 
    - Introduction: Main-Lab/Deployment/dep_intro.md
    - Control Hub:
      - Preparing Your Devices: Main-Lab/Deployment/dep_controlHub/dep_controlHub_prepDevices.md
      - Utilizing Configuration Templates: Main-Lab/Deployment/dep_controlHub/dep_controlHub_configTemplates.md
      - Org-Wide Templates: Main-Lab/Deployment/dep_controlHub/dep_controlHub_orgTemplates.md
      - Run Commands:  Main-Lab/Deployment/dep_controlHub/dep_controlHub_runCommands.md
      - Deploy UI Extensions:  Main-Lab/Deployment/dep_controlHub/dep_controlHub_deployExtensions.md
      - Deploy Macros:  Main-Lab/Deployment/dep_controlHub/dep_controlHub_deployMacros.md
    - CE-Deploy:
      - Local vs Cloud Authentication: Main-Lab/Deployment/dep_ceDeploy/dep_ceDeploy_cloud_localVsCloud.md
      - Download Webex Token: Main-Lab/Deployment/dep_ceDeploy/dep_ceDeploy_cloud_downloadToken.md
      - Run Commands: Main-Lab/Deployment/dep_ceDeploy/dep_ceDeploy_cloud_runCommands.md
      - Deploy Branding: Main-Lab/Deployment/dep_ceDeploy/dep_ceDeploy_cloud_deployBranding.md
      - Deploy Macros: Main-Lab/Deployment/dep_ceDeploy/dep_ceDeploy_cloud_deployMacros.md
      - Deploy UI Extensions: Main-Lab/Deployment/dep_ceDeploy/dep_ceDeploy_cloud_deployExtensions.md
      - Deploy Local User Accounts: Main-Lab/Deployment/dep_ceDeploy/dep_ceDeploy_cloud_deployLocalUsers.md
      - Device Backups and Logs: Main-Lab/Deployment/dep_ceDeploy/dep_ceDeploy_cloud_backupsAndLogs.md
      - Tools: Main-Lab/Deployment/dep_ceDeploy/dep_ceDeploy_cloud_tools.md
      - Dashboards: Main-Lab/Deployment/dep_ceDeploy/dep_ceDeploy_cloud_dashboards.md
    - Conclusion: Main-Lab/Deployment/dep_conclusion.md
  - Resources: 
    - Lab Tools: Main-Lab/Resources/res_tools.md
    - Guides: Main-Lab/Resources/res_guides.md
    - Communities: Main-Lab/Resources/res_communities.md
labVariables: 
  devNotice: | 
    #

    !!! important "Under Construction"

        This Lab is under development for Webex One 2025

        If you're looking to use the collateral made for WebexOne 2024, please use the link below

        [https://webexcc-sa.github.io/LAB-1451-24/](https://webexcc-sa.github.io/LAB-1451-24/){:target="_blank"}
  rxp:
    x: placeholder
  pxp:
    x: placeholder
  prq:
    x: placeholder
  dep:
    x: placeholder
  res: 
    x: placeholder