---
site_name: "LAB-1451: Deep-dive into Cisco devices xAPIs" # This must begin with the session ID, e.g. LABXXX-1234 This is my Cisco Live Lab
dev_addr: 127.0.0.1:8001
site_description: "Deep-dive into Cisco devices xAPIs" # must be same as "site_name"
site_author: Bobby McGonigle, Christopher Norman
copyright: Copyright &copy; 2025 Cisco
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - navigation.footer
    - search.suggest
    - content.code.copy
    - toc.integrate
    - content.tooltips
    - content.footnote.tooltips
  custom_dir: docs/overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: template_assets/webexLogo91.png
  favicon: template_assets/webex75.png
extra:
  generator: false
  repo: "https://github.com/WebexCC-SA/LAB-1451.git"
  site_event: test
extra_css:
  - stylesheets/extra.css
  - stylesheets/customTextHighlight.css
extra_javascript:
  - template_assets/js/newLoad.js
  - template_assets/js/setInfo.js
plugins:
  - search
  - macros
  # - with-pdf:
  #     cover_title: LABXXX-1234
  #     cover_subtitle: My famous WebexOne Lab
  #     cover_logo: template_assets/Wx1_25_PDF_image.jpg

  - glightbox:
      touchNavigation: true
      loop: false
      effect: fade
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: false
      skip_classes:
      - custom-skip-class-name
      auto_caption: true
      caption_position: top
markdown_extensions:
  - attr_list
  - md_in_html
  - abbr
  - admonition
  - def_list
  - footnotes
  - meta
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
      
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # Extensions below enabled by Bobby
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
nav:
  - Home&nbsp<i class="fa-solid fa-house" style="color:#B197FC;"></i>: index.md
  - Lab Setup&nbsp<i class="fa-solid fa-gear"></i>: Main-Lab/Setup/stp_intro.md # Changed from Lab Prerequisites. Moved Prerequisites to each major lab folder
  - "RoomOS xAPI & Extensions&nbsp<i class=\"fa-solid fa-video\" style=\"color: #428bff;\"></i>": 
    - RoomOS Introduction: Main-Lab/RoomOS/rxp_intro.md
    - RoomOS Lab Prerequisites: Main-Lab/RoomOS/rxp_prerequisites.md
    - RoomOS xAPI:
      - What are RoomOS xAPI: Main-Lab/RoomOS/rxp_xapi/rxp_xapi_intro.md
      - SSH/Serial <sup><sup>{{ config.cProps.rxp.sectionIds.ssh }}</sup></sup>: Main-Lab/RoomOS/rxp_xapi/rxp_xapi_sshSerial.md
      - HTTP <sup><sup>{{ config.cProps.rxp.sectionIds.http }}</sup></sup>: Main-Lab/RoomOS/rxp_xapi/rxp_xapi_http.md
      - WebSockets <sup><sup>{{ config.cProps.rxp.sectionIds.websocket }}</sup></sup>: Main-Lab/RoomOS/rxp_xapi/rxp_xapi_websockets.md
      - Webex Cloud <sup><sup>{{ config.cProps.rxp.sectionIds.cloud }}</sup></sup>: Main-Lab/RoomOS/rxp_xapi/rxp_xapi_cloud.md
      - Macros <sup><sup>{{ config.cProps.rxp.sectionIds.macro }}</sup></sup>: Main-Lab/RoomOS/rxp_xapi/rxp_xapi_macros.md
    - RoomOS Extensions: 
      - What are RoomOS Extensions: Main-Lab/RoomOS/rxp_userInterface/rxp_ui_intro.md
    - Solution Exercises:
      - RoomOS Exercises Introduction: Main-Lab/RoomOS/rxp_exercises/rxp_exe_intro.md
  - "PhoneOS xAPI&nbsp<i class=\"fa-solid fa-phone\" style=\"color: #00c753;\"></i>": 
    - PhoneOS Introduction: Main-Lab/PhoneOS/pxp_intro.md
    - PhoneOS Lab Prerequisites: Main-Lab/PhoneOS/pxp_prerequisites.md
    # - PhoneOS Conclusion: Main-Lab/Deployment/dep_conclusion.md
  - "Deployment&nbsp<i class=\"fa-solid fa-cloud-arrow-up\" style=\"color: #ff0000;\"></i>": 
    - Deployment Introduction: Main-Lab/Deployment/dep_intro.md
    - Deployment Lab Prerequisites: Main-Lab/Deployment/dep_prerequisites.md
    - Control Hub:
      - Preparing Your Devices <sup><sup>{{config.cProps.dep.sectionIds.cH}}.1</sup></sup>: Main-Lab/Deployment/dep_controlHub/dep_controlHub_prepDevices.md
      - Configuration Templates <sup><sup>{{config.cProps.dep.sectionIds.cH}}.2</sup></sup>: Main-Lab/Deployment/dep_controlHub/dep_controlHub_configTemplates.md
      - Org-Wide Templates <sup><sup>{{config.cProps.dep.sectionIds.cH}}.3</sup></sup>: Main-Lab/Deployment/dep_controlHub/dep_controlHub_orgTemplates.md
      - Run Commands <sup><sup>{{config.cProps.dep.sectionIds.cH}}.4</sup></sup>:  Main-Lab/Deployment/dep_controlHub/dep_controlHub_runCommands.md
      - Deploy UI Extensions <sup><sup>{{config.cProps.dep.sectionIds.cH}}.5</sup></sup>:  Main-Lab/Deployment/dep_controlHub/dep_controlHub_deployExtensions.md
      - Deploy Macros <sup><sup>{{config.cProps.dep.sectionIds.cH}}.6</sup></sup>:  Main-Lab/Deployment/dep_controlHub/dep_controlHub_deployMacros.md
    - CE-Deploy:
      - Local vs Cloud Authentication <sup><sup>{{config.cProps.dep.sectionIds.cD}}.1</sup></sup>: Main-Lab/Deployment/dep_ceDeploy/dep_ceDeploy_cloud_localVsCloud.md
      - Download Webex Token <sup><sup>{{config.cProps.dep.sectionIds.cH}}.2</sup></sup>: Main-Lab/Deployment/dep_ceDeploy/dep_ceDeploy_cloud_downloadToken.md
      - Run Commands <sup><sup>{{config.cProps.dep.sectionIds.cH}}.3</sup></sup>: Main-Lab/Deployment/dep_ceDeploy/dep_ceDeploy_cloud_runCommands.md
      - Deploy Branding <sup><sup>{{config.cProps.dep.sectionIds.cH}}.4</sup></sup>: Main-Lab/Deployment/dep_ceDeploy/dep_ceDeploy_cloud_deployBranding.md
      - Deploy Macros <sup><sup>{{config.cProps.dep.sectionIds.cH}}.5</sup></sup>: Main-Lab/Deployment/dep_ceDeploy/dep_ceDeploy_cloud_deployMacros.md
      - Deploy UI Extensions <sup><sup>{{config.cProps.dep.sectionIds.cH}}.6</sup></sup>: Main-Lab/Deployment/dep_ceDeploy/dep_ceDeploy_cloud_deployExtensions.md
      - Deploy Local User Accounts <sup><sup>{{config.cProps.dep.sectionIds.cH}}.7</sup></sup>: Main-Lab/Deployment/dep_ceDeploy/dep_ceDeploy_cloud_deployLocalUsers.md
      - Device Backups and Logs <sup><sup>{{config.cProps.dep.sectionIds.cH}}.8</sup></sup>: Main-Lab/Deployment/dep_ceDeploy/dep_ceDeploy_cloud_backupsAndLogs.md
      - Tools <sup><sup>{{config.cProps.dep.sectionIds.cH}}.9</sup></sup>: Main-Lab/Deployment/dep_ceDeploy/dep_ceDeploy_cloud_tools.md
      - Dashboards <sup><sup>{{config.cProps.dep.sectionIds.cH}}.10</sup></sup>: Main-Lab/Deployment/dep_ceDeploy/dep_ceDeploy_cloud_dashboards.md
    - Deployment Conclusion: Main-Lab/Deployment/dep_conclusion.md
  - Resources&nbsp<i class="fa-solid fa-globe" style="color:#ffd903;"></i>: 
    - Lab Tools: Main-Lab/Resources/res_tools.md
    - Guides: Main-Lab/Resources/res_guides.md
    - Communities: Main-Lab/Resources/res_communities.md
cProps:
  auth: 
    roomosIp: <copy><w class="ipAddress">[ROOMOS_IP_ADDRESS]</w></copy>
    roomosUser: <copy><w class="username">[ROOMOS_USERNAME]</w></copy>
    roomosPass: <copy><w class="password">[ROOMOS_PASSWORD]</w></copy>
    devToken: <copy><w class="webexToken">[WEBEX_TOKEN]</w></copy>
  devNotice: | 
    !!! important "Under Construction"

        This Lab is under development for Webex One 2025

        If you're looking to use the collateral made for WebexOne 2024, please use the link below

        [https://webexcc-sa.github.io/LAB-1451-24/](https://webexcc-sa.github.io/LAB-1451-24/){:target="_blank"}
  rxp:
    x: placeholder
    name: RoomOS xAPI & Extensions
    secNotice: |
  
    sectionIds:
      ssh: rxp-1
      http: rxp-2
      websocket: rxp-3
      cloud: rxp-4
      macro: rxp-5
      sdk: rxp-6
      exercises: rxp-7
  pxp:
    x: placeholder
  stp:
    x: placeholder
  dep:
    sectionIds:
      cH: dep-1
      cD: dep-2
  res: 
    x: placeholder